services:
  postgres:
    image: postgres:15.4
    container_name: prg_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  polarag_backend:
    container_name: prg_back
    build: ./backend/.
    env_file: .env
    volumes:
      - ./web_entrypoint.sh:/entrypoint.sh
    command: [ "bash", "/entrypoint.sh" ]
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres

  polarag_frontend:
    container_name: prg_front
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
    build: ./frontend/.
    volumes:
      - ./web_front_entrypoint.sh:/entrypoint.sh
    command: [ "sh", "-c", "bash /entrypoint.sh" ]
    restart: unless-stopped
    ports:
      - 3000:3000

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    ports:
      - ${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}
      - ${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}
    expose:
      - ${QDRANT_HTTP_PORT}
      - ${QDRANT_GRPC_PORT}
      - 6335
    configs:
      - source: qdrant_config
        target: ${QDRANT_CONFIG_PATH}
    volumes:
      - ./qdrant_data:/qdrant/storage

  vllm:
    image: vllm/vllm-openai:latest
    restart: unless-stopped
    container_name: vllm
    env_file: .env
    ports:
      - ${VLLM_PORT}:${VLLM_PORT}
      - ${VLLM_CONTROLLER_PORT}:${VLLM_CONTROLLER_PORT}
    expose:
      - ${VLLM_PORT}
      - ${VLLM_CONTROLLER_PORT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/vllm/entrypoint.sh"]
    volumes:
      - ./vllm:/vllm

volumes:
  postgres_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO
