services:
  postgres:
    image: postgres:15.4
    container_name: prg_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - 6543:5432
    restart: always

  polarag_backend:
    container_name: prg_back
    build: ./backend/web/.
    env_file: .env
    volumes:
      - ./web_entrypoint.sh:/entrypoint.sh
      - ./prg_back:/home/plateerag
    command: [ "bash", "/entrypoint.sh" ]
    stdin_open: true
    tty: true
    restart: always
    ports:
      - ${NEXT_PUBLIC_BACKEND_PORT}:8000
    depends_on:
      - postgres

  polarag_frontend:
    container_name: prg_front
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
    build: ./frontend/web-front/.
    volumes:
      - ./web_front_entrypoint.sh:/entrypoint.sh
      - ./prg_front:/home/plateerag
    command: [ "sh", "-c", "bash /entrypoint.sh" ]
    restart: always
    ports:
      - ${NEXT_PUBLIC_FRONTEND_PORT}:3000

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - ${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}
      - ${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}
    expose:
      - ${QDRANT_HTTP_PORT}
      - ${QDRANT_GRPC_PORT}
      - 6335
    configs:
      - source: qdrant_config
        target: ${QDRANT_CONFIG_PATH}
    volumes:
      - ./qdrant_data:/qdrant/storage

volumes:
  postgres_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO
